In [1]:
pip install keras

In [2]:
import keras 
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import RMSprop

batch_size = 128
num_classes = 10
epochs = 20

(x_train, y_train), (x_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [3]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [4]:
x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')

60000 train samples
10000 test samples


In [5]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [6]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [7]:
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [8]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [9]:
model = Sequential()

In [10]:
model.add(Dense(512, activation='relu', input_shape=(784, )))
model.add(Dropout(0.2))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(num_classes, activation='softmax'))

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 512)               401920    
_________________________________________________________________
dropout (Dropout)            (None, 512)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 512)               262656    
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                5130      
Total params: 669,706
Trainable params: 669,706
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.compile(loss='categorical_crossentropy',
 optimizer=RMSprop(),
 metrics=['accuracy'])

In [13]:
history = model.fit(x_train, y_train,
 batch_size=batch_size,
 epochs=epochs,
 verbose=1,
 validation_data=(x_test, y_test))

Epoch 1/20
469/469 [==============================] - 11s 22ms/step - loss: 0.4271 - accuracy: 0.8645 - val_loss: 0.1483 - val_accuracy: 0.9530
Epoch 2/20
469/469 [==============================] - 10s 21ms/step - loss: 0.1006 - accuracy: 0.9693 - val_loss: 0.0901 - val_accuracy: 0.9727
Epoch 3/20
469/469 [==============================] - 10s 21ms/step - loss: 0.0720 - accuracy: 0.9778 - val_loss: 0.0679 - val_accuracy: 0.9805
Epoch 4/20
469/469 [==============================] - 10s 20ms/step - loss: 0.0547 - accuracy: 0.9830 - val_loss: 0.0825 - val_accuracy: 0.9784
Epoch 5/20
469/469 [==============================] - 10s 20ms/step - loss: 0.0455 - accuracy: 0.9859 - val_loss: 0.0799 - val_accuracy: 0.9775
Epoch 6/20
469/469 [==============================] - 10s 21ms/step - loss: 0.0411 - accuracy: 0.9877 - val_loss: 0.0823 - val_accuracy: 0.9817
Epoch 7/20
469/469 [==============================] - 9s 20ms/step - loss: 0.0345 - accuracy: 0.9902 - val_loss: 0.0777 - val_accuracy: 

In [14]:
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.11307275295257568
Test accuracy: 0.984499990940094


In [15]:
model.add(Dense(10, activation='relu', input_shape=(784, )))
model.add(Dropout(0.2))
model.add(Dense(10, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(num_classes, activation='softmax'))

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 512)               401920    
_________________________________________________________________
dropout (Dropout)            (None, 512)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 512)               262656    
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                5130      
_________________________________________________________________
dense_3 (Dense)              (None, 10)                110       
_________________________________________________________________
dropout_2 (Dropout)          (None, 10)                0

In [17]:
# 学習は、scrkit-learnと同様fitで記述できる
history = model.fit(x_train, y_train,
 batch_size=batch_size,
 epochs=epochs,
 verbose=1,
 validation_data=(x_test, y_test))

# 評価はevaluateで行う
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Epoch 1/20
469/469 [==============================] - 10s 21ms/step - loss: 0.0156 - accuracy: 0.9954 - val_loss: 0.1242 - val_accuracy: 0.9832
Epoch 2/20
469/469 [==============================] - 10s 21ms/step - loss: 0.0164 - accuracy: 0.9956 - val_loss: 0.1334 - val_accuracy: 0.9829
Epoch 3/20
469/469 [==============================] - 10s 21ms/step - loss: 0.0162 - accuracy: 0.9958 - val_loss: 0.1402 - val_accuracy: 0.9834
Epoch 4/20
469/469 [==============================] - 10s 22ms/step - loss: 0.0143 - accuracy: 0.9960 - val_loss: 0.1461 - val_accuracy: 0.9829
Epoch 5/20
469/469 [==============================] - 10s 21ms/step - loss: 0.0143 - accuracy: 0.9962 - val_loss: 0.1356 - val_accuracy: 0.9846
Epoch 6/20
469/469 [==============================] - 10s 21ms/step - loss: 0.0160 - accuracy: 0.9962 - val_loss: 0.1449 - val_accuracy: 0.9843
Epoch 7/20
469/469 [==============================] - 10s 21ms/step - loss: 0.0155 - accuracy: 0.9960 - val_loss: 0.1392 - val_accuracy: