In [1]:
import numpy as np

A = np.eye(4)
first, second = np.vsplit(A, [3])
second.T

array([[0.],
       [0.],
       [0.],
       [1.]])

In [8]:
import numpy as np

A = np.eye(4)
first, second = np.vsplit(A, [3])
first

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [6]:
second

array([[0., 0., 0., 1.]])

In [9]:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
B = A.flatten()
A[1,:]=0
B = B.reshape(6,1)
B[-1]

array([6])

In [11]:
A = np.array([[1,2,3],[4,5,6]])
B = A.flatten()
A[1,:]=0
B

array([1, 2, 3, 4, 5, 6])

In [12]:
B = B.reshape(6,1)
B

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [13]:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
B = A.flatten()
A[1,:]=0
B[-1]

6