In [ ]:
names = ['spam', 'ham', 'eggs' ]
lens =[]
for name in names:
    lens.append(name)

lens


['spam', 'ham', 'eggs']

In [ ]:
lens('spam')

TypeError: ignored

In [ ]:
import numpy as np
a = np.full((1, 5), np.e).T.ravel()
a

array([2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183])

In [ ]:
import numpy as np
a = np.full((1, 5), np.e)
a

array([[2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183]])

In [ ]:
import numpy as np
a = np.full(1, 5).T.ravel
a

<function ndarray.ravel>

In [ ]:
b = np.linspace(0, 1, 5)
b

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
a = np.full((1, 5), np.e).T.ravel()
b = np.linspace(0, 1, 5)
c = np.hstack([a, b])
c

array([2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183,
       0.        , 0.25      , 0.5       , 0.75      , 1.        ])

In [8]:
import numpy as np

a = np.array([[0,1],
              [2,3]])

b = np.array([[0,1],[3,4]])

a*b

array([[ 0,  1],
       [ 6, 12]])

In [17]:
import numpy as np

a = np.array([[0,1,10],[0,1,10]])
a2 = a.reshape(2,3)
a * a2

array([[  0,   1, 100],
       [  0,   1, 100]])

In [11]:
a

array([[ 0,  1, 10],
       [ 0,  1, 10]])

In [12]:
a2

array([[ 0,  1],
       [10,  0],
       [ 1, 10]])

In [18]:
import numpy as np

A = np.eye(3)
B = np.count_nonzero(A)
C = np.sum(A)

In [19]:
B

3