In [3]:
import numpy as np

a = np.array([[0,1,10],[0,1,10]])
b = np.array([[100],[100]])
c = np.concatenate([a,b],axis=1)
c
c = c.reshape(4,2)
np.dot(c, b)

array([[  100],
       [11000],
       [  100],
       [11000]])

In [7]:
a = np.array([[0,1,10],[0,1,10]])
b = np.array([[100],[100]])
c = np.concatenate([a,b],axis=1)
c

array([[  0,   1,  10, 100],
       [  0,   1,  10, 100]])

In [15]:
import numpy as np

A = np.eye(4)
first, second = np.hsplit(A, [1])
first


array([[1.],
       [0.],
       [0.],
       [0.]])

In [11]:
import numpy as np

A = np.eye(4)
A

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])