In [1]:
import numpy as np

A = np.array([[0, 1, 2, 3, 4]])
B = np.full((1, 5), 1)
A[A>=B]

array([1, 2, 3, 4])

In [2]:
B

array([[1, 1, 1, 1, 1]])

In [4]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [5]:
import copy 

A = [1,2,3]
B = A.copy()
A.append(4)
B

[1, 2, 3]

In [7]:
A.append(4)
A

[1, 2, 3, 4, 4, 4]

In [9]:
import numpy as np

a = np.array([[0,1,10],[0,1,10]])
b = a.copy()
a = a.reshape(3,2)
np.dot(a, b)

array([[  0,   1,  10],
       [  0,  10, 100],
       [  0,  11, 110]])

In [10]:
np.multiply(a,b)

ValueError: ignored